services:
  postgresql:
    image:
      postgres:latest
    restart: always
    volumes: # PostgreSql 컨테이너에서 데이터를 로컬 파일 시스템에 저장하여 컨테이너 삭제 후에도 데이터 유지
      - ./data/ecommerce-db:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: localpw

  prometheus:
    image: prom/prometheus:latest
    restart: always
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  pushgateway:
    image: prom/pushgateway:latest
    restart: always
    ports:
      - "9091:9091"

  grafana:
    image: grafana/grafana:latest
    restart: always
    ports:
      - "3000:3000"