spring:
  application:
    name: ecommerce-batch

  datasource:
    url: jdbc:postgresql://localhost:5433/postgres?profileSQL=true
    username: postgres
    password: localpw
    hikari:
      maximum-pool-size: 200
  batch:
    jdbc:
      initialize-schema: always


logging:
  level:
    root: INFO
#    org.springframework.jdbc.core.JdbcTemplate: DEBUG
#    org.springframework.jdbc.core.StatementCreatorUtils: DEBUG

prometheus:
  job:
    name: spring-batch
  pushgateway:
    enabled: true
    url: localhost:9091